Add checks for release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -110,6 +110,12 @@ jobs:
       version: ${{ needs.build.outputs.version }}
     runs-on: ubuntu-latest
     steps:
+      - name: Check Tag
+        run: |
+          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            echo "Found invalid version '$version'" >&2
+            exit 1
+          fi
       - name: Make Directory
         run: mkdir artifacts/
       - name: Download Build Artifacts
@@ -122,4 +128,5 @@ jobs:
         with:
           tag_name: v${{ needs.build.outputs.version }}
           files: artifacts/*
+          if-no-files-found: error
 
